### ISSUE TITLE
Epic: MVP Wind Tunnel

### ISSUE THREAD

**Issue by neonphog** [holochain/wind-tunnel#106]
Minimum WT tasks required to get holochain back to stable.

- [ ] https://github.com/holochain/wind-tunnel/issues/6
- [ ] https://github.com/holochain/wind-tunnel/issues/29

May not be required:

- [ ] https://github.com/holochain/wind-tunnel/issues/69

**Comment by cdunster** [comment]
I believe that we are no longer tracking Epics in this way and instead we are using the GitHub-projects' built-in Epics so I am closing this issue.
